### ISSUE TITLE
Support common documentation formats

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Library-Analyzer#14]
- [x] Refactor NumpyDocParser to use docstring-parser
- [ ] Safe-DS/Library-Analyzer#19 
- [ ] Safe-DS/Library-Analyzer#18 
- [x] Safe-DS/Library-Analyzer#17 
- [x] Safe-DS/Library-Analyzer#16 
- [ ] Safe-DS/Library-Analyzer#15 
- [ ] Safe-DS/Library-Analyzer#10

### Additional Context

* Examples of the different formats: https://realpython.com/documenting-python-code/#google-docstrings-example
* ~`pyment` can detect the used documentation format: https://github.com/dadadel/pyment/blob/2c10b1c64093adbce8db369a3db4321e6c3c7c32/pyment/docstring.py#L647~
* ~[`pdoc`](https://github.com/mitmproxy/pdoc) might also be helpful for this, particularly the conversion from a docstring format to Markdown: https://pdoc.dev/docs/pdoc/docstrings.html~
* [docstring_parser](https://github.com/rr-/docstring_parser) seems to be exactly what we are looking for
